name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker:
    uses: koenverburg/.github/.github/workflows/docker-build.yaml@main
    secrets:
      docker_token: ${{ secrets.SITE_GHCR_TOKEN }}
    with:
      registry: ghcr.io
      image_name: koenverburg/site/site-links
      dockerfile_path: ./Dockerfile
      tags: ${{ github.run_number }}
