name: static build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run build

      - run: npm run export

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build-output
          path: ./dist
          retention-days: 2

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download nextjs output
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build-output
          path: ./dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: links.koenverburg.dev
          publish_dir: ./dist
